### ISSUE TITLE
Language matching query does not exist.

### ISSUE THREAD

**Issue by markus2330** [wger-project/helm-charts#2]
I used the helm chart as described in https://github.com/sedadas/helm-charts

Everything seemed to have started up successfully:
```
NAME                    READY   STATUS    RESTARTS   AGE
wger-app-0              1/1     Running   0          3m5s
wger-postgresql-0       1/1     Running   0          3m5s
wger-redis-master-0     1/1     Running   0          3m5s
wger-redis-replicas-0   1/1     Running   0          3m5s
wger-redis-replicas-1   1/1     Running   0          48s
wger-redis-replicas-2   0/1     Running   0          21s
```

but when I try to:
```
kubectl proxy
```

and visit http://localhost:8001/api/v1/namespaces/wger/services/wger-http:8000/proxy/en

I get following error:

```
<h1>DoesNotExist
       at /en/software/features</h1>
  <pre class="exception_value">Language matching query does not exist.</pre>
  

Request Method: | GET
-- | --
http://192.168.39.79:8443/en/software/features
3.2.11
DoesNotExist
Language matching query does not exist.
/usr/local/lib/python3.9/dist-packages/django/db/models/query.py, line 435, in get
/usr/bin/python3
3.9.5
['/home/wger/src',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/home/wger/.local/lib/python3.9/site-packages',  '/home/wger/src',  '/usr/local/lib/python3.9/dist-packages',  '/usr/lib/python3/dist-packages',  '/home/wger/src']
Mon, 24 Jan 2022 15:05:24 +0000



Environment:


Request Method: GET
Request URL: http://192.168.39.79:8443/en/software/features

Django Version: 3.2.11
Python Version: 3.9.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_extensions',
 'storages',
 'wger.config',
 'wger.core',
 'wger.mailer',
 'wger.exercises',
 'wger.gym',
 'wger.manager',
 'wger.nutrition',
 'wger.software',
 'wger.utils',
 'wger.weight',
 'wger.gallery',
 'wger.measurements',
 'captcha',
 'django.contrib.sitemaps',
 'easy_thumbnails',
 'compressor',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_bootstrap_breadcrumbs',
 'corsheaders')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'wger.utils.middleware.JavascriptAJAXRedirectionMiddleware',
 'wger.utils.middleware.WgerAuthenticationMiddleware',
 'wger.utils.middleware.RobotsExclusionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback (most recent call last):
  File "/home/wger/src/wger/utils/language.py", line 54, in load_language
    language = Language.objects.get(short_name=used_language)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Language matching query does not exist.), another exception occurred:
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wger/src/wger/software/views.py", line 37, in features
    return render(request, 'features.html', context)
  File "/usr/local/lib/python3.9/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.9/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.9/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/dist-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/home/wger/src/wger/utils/context_processor.py", line 28, in processor
    language = load_language()
  File "/home/wger/src/wger/utils/language.py", line 57, in load_language
    language = Language.objects.get(short_name="en")
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /en/software/features
Exception Value: Language matching query does not exist.

```

**Comment by markus2330** [comment]
At least some setup seems to have happened:

```
kubectl logs wger-app-0 -n wger
Waiting for postgres...
PostgreSQL started :)
*** Database does not exist, creating one now
Operations to perform:
  Apply all migrations: auth, authtoken, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
Running migrations:
  Applying contenttypes.0001_initial... OK
...
  Applying weight.0003_auto_20160416_1030... OK
Installed 1 object(s) from 1 fixture(s)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django_redis/cache.py", line 103, in delete
    result = self.client.delete(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django_redis/client/default.py", line 375, in delete
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Problem installing fixture '/home/wger/src/wger/core/fixtures/languages.json': Error 111 connecting to wger-redis-master:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.9/dist-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.9/dist-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.9/dist-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/wger/src/wger/tasks.py", line 97, in bootstrap
    load_fixtures(context, settings_path=settings_path)
  File "/usr/local/lib/python3.9/dist-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/wger/src/wger/tasks.py", line 237, in load_fixtures
    call_command("loaddata", "languages.json")
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.9/dist-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.9/dist-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/wger/src/wger/config/signals.py", line 47, in init_language_config
    config.save()
  File "/home/wger/src/wger/config/models/language_config.py", line 83, in save
    cache.delete(cache_mapper.get_language_config_key(self.language, self.item))
  File "/usr/local/lib/python3.9/dist-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/usr/local/lib/python3.9/dist-packages/django_redis/client/default.py", line 373, in delete
    return client.delete(self.make_key(key, version=version, prefix=prefix))
  File "/usr/local/lib/python3.9/dist-packages/redis/commands/core.py", line 1177, in delete
    return self.execute_command("DEL", *names)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1173, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1358, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 611, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Problem installing fixture '/home/wger/src/wger/core/fixtures/languages.json': Error 111 connecting to wger-redis-master:6379. Connection refused.
Traceback (most recent call last):
  File "/home/wger/.local/bin/wger", line 33, in <module>
    sys.exit(load_entry_point('wger', 'console_scripts', 'wger')())
  File "/home/wger/src/wger/__main__.py", line 40, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/usr/local/lib/python3.9/dist-packages/invoke/__init__.py", line 48, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/context.py", line 95, in run
    return self._run(runner, command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/usr/local/lib/python3.9/dist-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke bootstrap'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)
```

**Comment by sedadas** [comment]
Hello @markus2330,
are you using a custom `values.yaml`? If so, could you please post it (with the secrets obfuscated) so that I can try to reproduce the issue.

**Comment by markus2330** [comment]
No, I did not change anything. I noticed that a few pods took quite long to start.

**Comment by sedadas** [comment]
Hi, I just managed to check this. It may happen when the app pod has started, but redis is not yet available.
I'll add an init container that checks for both postgres and redis before starting. You can then test it out.
